[package]
name = "tree-sitter-bend2"
description = "Bend2 tree-sitter-parser"
version = "0.2.0"
authors = ["Thybault Alabarbe <thybault.alabarbe@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "bend2"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/soulthym/tree-sitter-bend2"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.9"
